### ISSUE TITLE
Brief case prop doesnt delete

### ISSUE THREAD

**Issue by CarlosVergikosk** [TrundleThaGreat/RadiantRP_Animations#2]
When i use the /e brief animations, i cant remove the brief case from my hands, already tried /e stuckprop, /e stop, X etc...

The only way i found to remove it, its if someone handcuff's me

**Comment by TrundleThaGreat** [comment]
The brief is actually considered a weapon, you can get rid of it by swapping to any weapon or selecting your fists. You can see on line 249 GiveWeaponToPed(player, 0x88C78EB7, 1, false, true) this is what we are using to spawn it in. I can probably set it up for /e stop or /e stuckprop to clear it.
